### PR TITLE
Additional affines

### PR DESCRIPTION
**Pull request by justusschock**
## Short Description
This PR adds additional Affine Transformations. It mainly includes Transformations around the image center and a resizing trafo.

### PR Implementer
This is a small checklist for the implementation details of this PR.
If you submit a PR, please look at these points (don't worry about the `RisingTeam`
and `Reviewer` workflows, the only purpose of those is to have a compact view of
the steps)

If there are any questions regarding code style or other conventions check out our 
[summary](https://github.com/PhoenixDL/rising/blob/master/CONTRIBUTING.md).

- [x] Implementation
- [ ] Docstrings & Typing
- [ ] Check `__all__` sections and `__init__`
- [ ] Unittests (look at the line coverage of your tests, the goal is 100%!)
- [ ] Update notebooks & documentation if necessary
- [ ] Pass all tests
- [ ] Add the checksum of the last implementation commit to the Changelog

### RisingTeam
<details>
  <summary>RisingTeam workflow</summary>

  - [x] Add pull request to project (optionally delete corresponding project note)
  - [x] Assign correct label (if you don't have permission to do this, someone will do it for you. 
      Please make sure to communicate the current status of the pr.)
  - [x] Does this PR close an Issue? (add `closes #IssueNumber` at the bottom if 
        not already in description)
</details>

### Reviewer
<details>
  <summary>Reviewer workflow</summary>
  
  - [ ] Do all tests pass? (Unittests, NotebookTests, Documentation)
  - [ ] Does the implementation follow `rising` design conventions?
  - [ ] Are the tests useful? (!!!) Are additional tests needed? 
        Can you think of critical points which should be covered in an additional test?
  - [ ] Optional: Check coverage locally / Check tests locally if GPU is necessary to execute
</details>

### CODE REVIEW

**Comment by mibaumgartner** [comment]
I would like to propose the naming convention: the default behaviour should be the rotation around the image center (consistent to other frameworks) and the current rotation (from the master branch) should be renamed to something differently (e.g. RotationOrigin)

**Comment by justusschock** [comment]
And same for scaling?

**Comment by justusschock** [comment]
Do you want to merge this despite the refactoring PR?

**Comment by mibaumgartner** [comment]
We need to undo my commit, rename the transforms, rename OriginMixin to something like CenterMixin and check the tests again
Not sure if we really need the origin transforms though .. but we could keep them if you want

**Comment by justusschock** [comment]
closed in favour of #31 and #32

**Pull request closed without merging**
